name: build-deploy-on-dockerhub

run-name: ${{ github.actor }} is building a Docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker imate
        run: docker build . -t weather:0.0.1
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Create docker image tag
        run: docker tag weather:0.0.1 ${{ secrets.DOCKER_USER_REGISTRY }}/weather:0.0.1
      - name: Push to docker hub
        run: docker push ${{ secrets.DOCKER_USER_REGISTRY }}/weather:0.0.1